# frozen_string_literal: true

source 'https://rubygems.org'

gem 'aws-sdk', '~> 3'
gem 'cocoapods'
gem 'fastlane'
gem 'logging'
gem 'minitar'
gem 'neovim'
gem 'nokogiri'
gem 'parallel'
gem 'parser'
gem 'pry'
gem 'pry-coolline'
gem 'recursive-open-struct'
gem 'rouge'
gem 'rubocop', '= 0.81'
gem 'ruby-stemmer'
gem 'solargraph'
gem 'xcode-install'
