" Incompatible to vi
set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

Bundle 'sickill/vim-pasta.git'
Bundle 'Townk/vim-autoclose.git'
Bundle 'markschabacker/cocoa.vim.git'
Bundle 'majutsushi/tagbar'
Bundle 'tpope/vim-fugitive.git'
Bundle 'othree/html5.vim.git'
Bundle 'mattn/zencoding-vim.git'
Bundle 'tsaleh/vim-matchit.git'
Bundle 'kien/ctrlp.vim.git'
Bundle 'altercation/vim-colors-solarized.git'
Bundle 'Soares/write.vim.git'
Bundle 'vim-scripts/YankRing.vim'
Bundle 'mileszs/ack.vim'
Bundle 'kshenoy/vim-signature'
Bundle 'Lokaltog/powerline'
Bundle 'Valloric/YouCompleteMe'
Bundle 'xolox/vim-session'
Bundle 'tpope/vim-dispatch'

set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim/

" How many lines of history VIM remembers
set history=1000

" Enables syntax highlighting
syntax on

" Enable plugins based on filetype
filetype plugin indent on

" Solarized all the way
set background=dark
colorscheme solarized

let mapleader = ","

" Tab doesn't expand, Tab-Size is 4 spaces
set softtabstop=4
set shiftwidth=4

" Smart indentation of lines
set smartindent

" Enables Statusbar
set laststatus=2

" Highlight searches
set hlsearch
" No idea, 'makes search act like modern browsers'
set incsearch

" For regular expressions
set magic

" Show matching brackets
set showmatch

" No error sounds
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Ignore case when searching, but not if keywords are capitalized
set ignorecase smartcase

" Turn off backups
set nobackup
set nowb
set noswapfile

" Allows Backspace to loop over everything
set backspace=indent,eol,start

" No Arrow keys
map <Left> <Nop>
map <Right> <Nop>
map <Up> <Nop>
map <Down> <Nop>

" Viewport will move if Cursor is 10 lines away from the edge
set so=10

" Show current position
set ruler

set showcmd

" Height of the command bar
set cmdheight=1

" Automatically reload file when it is changed from the outside
set autoread

" Set default encoding to utf-8
set encoding=utf8

" Change split with Ctrl+Direction
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

set number
set rnu "relative line numbers

set guioptions-=T "No top toolbar
set guioptions-=r "no right scrollbar
set guioptions-=L "no left scrollbar

set completeopt=menu,menuone,longest

nmap <leader>l :TagbarToggle<CR>

set guifont=Menlo\ for\ Powerline "use patched font for Powerline
let g:Powerline_symbols='fancy' "use fancy symbols like arrows 
"let g:Powerline_theme='skwp'
let g:Powerline_colorscheme="skwp"

let g:ctrlp_map='<leader>p'
let g:ctlp_cmd='CtrlP'
