#!/usr/bin/env sh

# bsp, stack or float
yabai -m config layout bsp

# Mouse-related settings
yabai -m config mouse_follows_focus on

yabai -m config mouse_modifier fn

# left-click + drag to resize the window
yabai -m config mouse_action1 resize
# right-click + drag to move the window
yabai -m config mouse_action2 move
# Swap windows when they are dragged on top of each other
yabai -m config mouse_drop_action swap

# Disable management for these apps:
yabai -m rule --add app="(^System Settings$)" manage=off
yabai -m rule --add app="(^Karabiner-Elements$)" manage=off
yabai -m rule --add app="(^Karabiner-EventViewer$)" manage=off
yabai -m rule --add app="(^Hammerspoon$)" manage=off
yabai -m rule --add app="(^FaceTime$)" manage=off
yabai -m rule --add app="(^Cisco AnyConnect Secure Mobility Client$)" manage=off
yabai -m rule --add app="(^Dash$)" manage=off
yabai -m rule --add app="(^.*iStat Menus Status.*$)" mouse_follows_focus=off manage=off
yabai -m rule --add app="(^Finder$)" title="Copying..." manage=off

# Re-focus an active window when closing the last window of an application
# See https://github.com/koekeishiya/yabai/issues/1445
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"

# vim:ft=bash
