promptToReturnFromSubprocess: false
git:
  paging:
    colorArg: always
    pager: delta --paging=never --true-color always --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  showFileTree: false
  showIcons: true
  showFileIcons: true
